"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['grib_gui.py']
DATA_FILES = []
OPTIONS = {'includes': 'wx.adv,wx.html,wx.xml'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
